* rich-minority-mode

Emacs package for hiding and/or highlighting the list of minor-modes
in the mode-line.

** Usage

To activate the enrichment of your minor-modes list, call =M-x
rich-minority-mode=, or add this to your init file:

#+begin_src emacs-lisp
(rich-minority-mode 1)
#+end_src

By default, this has a couple of small effects (provided as examples)
it is up to you to customize it to your liking with the following
three variables:

- rm-excluded-modes :: List of minor mode names that will be hidden
     from the minor-modes list. Use this to hide *only* a few modes that
     are always active and don't really contribute information.
- rm-included-modes :: List of minor mode names that are allowed on
     the minor-modes list. Use this to hide *all but* a few modes.
- rm-text-properties :: List text properties to apply to each
     minor-mode lighter. For instance, by default we highlight =Ovwrt=
     with a red face, so you always know if you're in =overwrite-mode=.

** Installation

This package is available fom Melpa, you may install it by calling
=M-x package-install=.

Alternatively, you can download it manually, place it in your
=load-path= and require it with

#+begin_src emacs-lisp
(require 'rich-minority)
#+end_src


